function verificar() {

var dato = document.getElementById("texto").value;
var busqueda = dato.toLowerCase();

var marcaauto = new Array();
marcaauto["toyota"] = "<article class=\"post clearfix\"><h2 class=\"post-title\"><a href=\"Vende_toyota1.html\">TOYOTA</a></h2><h2 class=\"post-title1\">Informaci&oacute;n del Vehiculo</a></h2><table width=\"200\" pa border=\"0\" class=\"info\"><tr><th><div align=\"left\">Modelo:</div></th><td>Yaris Hatchback</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;11,800.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2011</td></tr><tr><th><div align=\"left\">Color:</div></th><td>Blanco, azul, gris y rojo</td></tr></table><a href=\"Vende_toyota1.html\"> Mas informacion Aqui</a><hr><article class=\"post clearfix\"><h2 class=\"img1\"><img src=\"../Imagenes/Mb/foto2.jpg\" align=\"left\" display: block;   alt=\"Foto 1\" height=\"150\" width=\"150\"/></h2><h2 class=\"post-title1\">Informaci&oacute;n del Vehiculo</a></h2><table width=\"200\" pa border=\"0\" class=\"info\"><tr><th><div align=\"left\">Modelo:</div></th><td>Corolla</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;<strike>12,000.00</strike></td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2009</td></tr><tr><th><div align=\"left\">Color:</div></th><td>Gris</td></tr><tr><th><div align=\"left\">Promocion:</div></th><td>&#36;10,000.00</td></tr></table><a href=\"Vende_toyota2.html\">mas informacion Aqui</a>";
marcaauto["nissan"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\"  border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>NISSAN</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Murano</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;7,250.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr></table><a href=\"se-vende-carro-nissan.html\">mas informacion Aqui</a>";
marcaauto["ford"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>FORD</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Explorer</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;7,900.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr><tr><th><div align=\"left\">Color:</div></th><td>Gris</td></tr></table><a href=\"se-vende-carro-ford.html\">mas informacion Aqui</a>";
marcaauto["bmw"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>BMW</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Z3</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;8,400.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr></table><a href=\"se-vende-carro-BMW.html\">mas informacion Aqui</a>";
marcaauto["mitsubishi"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Mitsubishi</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Lancer</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;9,300.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2008</td></tr></table><a href=\"se-vende-carro-Mitsubishi.html\">mas informacion Aqui</a>";
marcaauto["dodge"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Dodge</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Caravan</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;4,500.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2001</td></tr></table><a href=\"se-vende-carro-dodge.html\">mas informacion Aqui</a>";
marcaauto["mercedez benz"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Mercedez Benz</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>C230 Kompressoe</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;13,500.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2005</td></tr></table><a href=\"se-vende-carro-MB.html\"> mas informacion Aqui</a>";
marcaauto["2001"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Dodge</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Caravan</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;4,500.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2001</td></tr></table><a href=\"se-vende-carro-dodge.html\">mas informacion Aqui</a>";
marcaauto["2003"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\"  border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>NISSAN</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Murano</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;7,250.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr></table><a href=\"se-vende-carro-nissan.html\">mas informacion Aqui</a><hr><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>FORD</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Explorer</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;7,900.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr></table><a href=\"se-vende-carro-ford.html\">mas informacion Aqui</a><hr><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>BMW</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Z3</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;8,400.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2003</td></tr></table><a href=\"se-vende-carro-BMW.html\">mas informacion Aqui</a>";
marcaauto["2005"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Mercedez Benz</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>C230 Kompressoe</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;13,500.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2005</td></tr></table><a href=\"se-vende-carro-MB.html\"> mas informacion Aqui</a>";
marcaauto["2008"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\" border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>Mitsubishi</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Lancer</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;9,300.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2008</td></tr></table><a href=\"se-vende-carro-Mitsubishi.html\">mas informacion Aqui</a>";
marcaauto["2009"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\"  border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>TOYOTA</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Corolla</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;<strike>12,000.00</strike></td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2009</td></tr><tr><th><div align=\"left\">Promocion:</div></th><td>&#36;10,000.00 </td></tr></table><a href=\"se-vende-carro-toyota2.html\">mas informacion Aqui</a>";
marcaauto["2011"] = "<h2 class=\"post-title\"><a href=\"#\">Buscador</a></h2><br><table width=\"200px\"  border=\"0\" class=\"info\"><tr><th><div align=\"left\">Marca:</div></th><td>TOYOTA</td></tr><tr><th><div align=\"left\">Modelo:</div></th><td>Yaris Hasback</td></tr><tr><th><div align=\"left\">Precio de venta</div></th><td>&#36;11,800.00</td></tr><tr><th><div align=\"left\">A&ntilde;o:</div></th><td>2011</td></tr></table><a href=\"se-vende-carro-toyota1.html\">mas informacion Aqui</a>";
marcaauto[13] = "<h2 class=\"post-title\">Buscador</h2><ul> Lamentablemente no encontramos lo que estabas busca: " + busqueda;
marcaauto[busqueda]

document.getElementById('divXCambiar').innerHTML = "" + marcaauto[busqueda] + "";
} 	